export const posts = [
  {
    id: 15,
    title: '소웨이 교재 팝니다',
    username: '최눈송',
    category: 'PROJECT',
    preview: '쪽지주세요!',
    createdAt: '2025-08-26 13:27:11',
    closed: false,
    likeCount: 0,
    comment: 0,
  },
  {
    id: 14,
    title: '자료구조 1분반 과제 답 맞춰보실 분',
    username: '박눈송',
    category: 'PROJECT',
    preview: '9시쯤에 같이 맞춰보실 분 3명 정도만 구합니다',
    createdAt: '2025-08-26 13:27:04',
    closed: false,
    likeCount: 0,
    comment: 0,
  },
  {
    id: 13,
    title: '복전하면 시간 관리가 많이 힘들까요?',
    username: '이눈송',
    category: 'PROJECT',
    preview:
      '복전하면 수업이 많이 늘어난다고 해서 고민 중이에요... 지금도 벅찬데 혹시 괜히 시작했다가 학점이나 시간관리만 힘들어지는 거 아닐까요?',
    createdAt: '2025-08-26 13:26:58',
    closed: false,
    likeCount: 0,
    comment: 0,
  },
  {
    id: 12,
    title: 'IT 취업 준비 특강 안내',
    username: '김눈송',
    category: 'PROJECT',
    preview:
      '교내 진로센터에서 ‘IT 분야 취업 전략’ 특강을 개최합니다. 네이버, 카카오 현직자 분을 모셔 개발 직무 면접 대비, 포트폴리오 작성, 인턴 ...',
    createdAt: '2025-08-26 13:26:51',
    closed: false,
    likeCount: 0,
    comment: 0,
  },
  {
    id: 11,
    title: '학과 주관 오픈소스 세미나 안내',
    username: '김눈송',
    category: 'PROJECT',
    preview:
      '이번 주 금요일 학과 주관 오픈소스 세미나가 열립니다. 최신 클라우드 기술과 오픈소스 프로젝트 사례 발표가 예정되어 있습니다.',
    createdAt: '2025-08-26 13:26:45',
    closed: false,
    likeCount: 0,
    comment: 0,
  },
  {
    id: 10,
    title: '교내 IT 해커톤 일정 안내',
    username: '김눈송',
    category: 'PROJECT',
    preview:
      '다음 달 초 교내 IT 해커톤이 열립니다. 참가 신청은 이번 주까지이며, 팀 단위 혹은 개인으로도 지원 가능합니다.',
    createdAt: '2025-08-26 13:26:39',
    closed: false,
    like: 0,
    comment: 0,
  },
  {
    id: 9,
    title: '클라우드 서비스 아이디어톤 팀원모집',
    username: '이눈송',
    category: 'PROJECT',
    preview:
      'AWS 주최 클라우드 아이디어톤에 참가할 팀원 구합니다. 주 1회 온라인 미팅 진행, 행사 전주에는 하루 종일 모여 리허설 예정입니다. 클라우드...',
    createdAt: '2025-08-26 13:26:32',
    closed: false,
    likeCount: 0,
    comment: 0,
  },
  {
    id: 8,
    title: 'AI 해커톤 참가할 프론트/백 구합니다',
    username: '최눈송',
    category: 'PROJECT',
    preview:
      '다음 달 서울에서 열리는 AI 해커톤에 참여할 예정입니다. 현재 팀에 기획 1, AI 모델 담당 1 있습니다. 2주 전부터 매 주말마다 만나 준...',
    createdAt: '2025-08-26 13:26:26',
    closed: false,
    likeCount: 0,
    comment: 0,
  },
  {
    id: 7,
    title: '데이터 분석 공모전 팀원 모집합니다 (2명 구인)',
    username: '박눈송',
    category: 'PROJECT',
    preview:
      '8월 개최 예정인 데이터톤에 참가 예정입니다. 제가 기획 맡고 데이터 분석 인원 2명 충원하려고 합니다. 파이썬 사용 가능하신 분이면 좋습니다....',
    createdAt: '2025-08-26 13:26:20',
    closed: false,
    likeCount: 0,
    comment: 0,
  },
  {
    id: 6,
    title: '데이터분석 기초 스터디',
    username: '박눈송',
    category: 'PROJECT',
    preview:
      '파이썬을 이용한 데이터분석 입문 스터디입니다. 주 1회 모여서 전공 교재 기반으로 스터디 진행하며, Kaggle 실습도 병행할 계획입니다.',
    createdAt: '2025-08-26 13:26:14',
    closed: false,
    likeCount: 0,
    comment: 0,
  },
  {
    id: 5,
    title: '인공지능 스터디',
    username: '이눈송',
    category: 'PROJECT',
    preview:
      '주 2회 대면으로 진행할 예정이며 저포함 4~5명 생각중입니다. 시간이나 장소 등 세부사항은 인원이 모이면 의논해서 정할 예정이며 궁금한 점은 ...',
    createdAt: '2025-08-26 13:26:09',
    closed: false,
    likeCount: 0,
    comment: 0,
  },
  {
    id: 4,
    title: '스프링 스터디',
    username: '김눈송',
    category: 'PROJECT',
    preview: '관심있으신분?',
    createdAt: '2025-08-26 13:25:53',
    closed: false,
    likeCount: 0,
    comment: 0,
  },
  {
    id: 3,
    title: '캡스톤디자인 공동 프로젝트',
    username: '박눈송',
    category: 'PROJECT',
    preview:
      '캡스톤디자인 과목을 함께 진행할 팀원을 찾습니다. 웹이나 앱 개발에 관심 있는 분이면 누구나 지원 가능하며, 개발 언어는 팀 내부에서 조율할 예...',
    createdAt: '2025-08-26 13:25:46',
    closed: false,
    likeCount: 0,
    comment: 0,
  },
  {
    id: 2,
    title: 'AI 해커톤 팀 모집',
    username: '이눈송',
    category: 'PROJECT',
    preview:
      '인공지능 해커톤 대회에 참가할 팀원을 모집합니다. 기획, 디자인, 개발자 모두 환영하며 주 2회 모임을 갖고 준비할 예정입니다. 관심 있으신 분...',
    createdAt: '2025-08-26 13:25:39',
    closed: false,
    likeCount: 0,
    comment: 0,
  },
  {
    id: 1,
    title: '프로젝트 팀원 모집',
    username: '김눈송',
    category: 'PROJECT',
    preview: '구합니다',
    createdAt: '2025-08-26 13:25:32',
    closed: false,
    likeCount: 0,
    comment: 0,
  },
];
